export const MIN_ZOOM = 0.5;
export const MAX_ZOOM = 4;
export const ZOOM_STEP = 1.15;

export const PDF_A4_WIDTH_MM = 210;
export const PDF_A4_HEIGHT_MM = 297;
export const PDF_A4_MARGIN_MM = 6;
export const PDF_EXPORT_EXTRA_BOTTOM_PADDING = 16;
export const PDF_PAGE_BREAK_GUARD_PX = 14;
export const CSS_PX_PER_MM = 96 / 25.4;
export const PDF_PT_PER_MM = 72 / 25.4;
export const PDF_PT_PER_CSS_PX = 72 / 96;
export const PDF_BROWSER_RASTER_SCALE = 3;
export const PDF_RASTER_MAX_CANVAS_PIXELS = 32_000_000;
export const PDF_RASTER_JPEG_QUALITY = 0.98;

export const PDF_BACKGROUND_PAGE_GAP = 12;
export const PDF_BACKGROUND_DESKTOP_MAX_WIDTH = 960;
export const PDF_BACKGROUND_MOBILE_MAX_WIDTH = 960;
export const PDF_BACKGROUND_DESKTOP_MAX_DPR = 1.6;
export const PDF_BACKGROUND_MOBILE_PREVIEW_DPR = 0.75;
export const PDF_BACKGROUND_MOBILE_SHARP_DPR = 1.6;
export const PDF_BACKGROUND_MOBILE_LONG_DOC_SHARP_DPR = 1.35;
export const PDF_BACKGROUND_DESKTOP_PREVIEW_DPR = 1;
export const PDF_BACKGROUND_DESKTOP_SHARP_DPR = 2;
export const PDF_BACKGROUND_SHARP_IDLE_MS = 650;
export const PDF_BACKGROUND_CACHE_CLEANUP_IDLE_MS = 900;
export const PDF_BACKGROUND_MOBILE_LONG_DOC_PAGES = 10;
export const PDF_BACKGROUND_MOBILE_DEFAULT_BUDGET = 3;
export const PDF_BACKGROUND_MOBILE_LONG_DOC_BUDGET = 2;
export const PDF_BACKGROUND_DESKTOP_RENDERED_PAGE_BUDGET = 9;

export const PDF_TEXT_HIGHLIGHT_COLOR = "#ffeb3b";
export const PDF_TEXT_UNDERLINE_COLOR = "#58bfd6";
export const PDF_TEXT_STRIKETHROUGH_COLOR = "#f2686c";
export const PDF_TEXT_NOTE_COLOR = "#8b5cf6";
export const PDF_TEXT_ANNOTATION_COLORS = ["#ffeb3b", "#47d764", "#4db3f7", "#f06292", "#9b7cf3"];

export const MARKDOWN_TILED_INK_MOBILE_MAX_SINGLE_PIXELS = 1_600_000;
export const MARKDOWN_TILED_INK_DESKTOP_MAX_SINGLE_PIXELS = 3_000_000;
export const MARKDOWN_TILED_INK_MOBILE_TILE_HEIGHT = 150;
export const MARKDOWN_TILED_INK_DESKTOP_TILE_HEIGHT = 1000;

export const INK_SHARP_IDLE_MS = 560;
export const INK_MOBILE_ACTIVE_DISPLAY_SCALE = 4.0;
export const INK_DESKTOP_ACTIVE_DISPLAY_SCALE = 4.0;
export const INK_MOBILE_MAX_DISPLAY_SCALE = 4.0;
export const INK_DESKTOP_MAX_DISPLAY_SCALE = 4.0;
